In [2]:
my_list =[1,2,3]


In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_mat =[[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10 ,2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(4)

array([0., 0., 0., 0.])

In [10]:
np.zeros(2,3)

TypeError: data type not understood

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5)

array([0.03549986, 0.5385069 , 0.64129639, 0.45775842, 0.58513118])

In [20]:
np.random.rand(5,5)

array([[0.00118316, 0.07306858, 0.42239736, 0.41983012, 0.20841437],
       [0.73031401, 0.62938529, 0.41033504, 0.91755281, 0.38748062],
       [0.58545919, 0.20219395, 0.46714242, 0.27942439, 0.2703896 ],
       [0.20296257, 0.3920293 , 0.37563396, 0.33239299, 0.29618929],
       [0.54064866, 0.08149582, 0.55641741, 0.06386355, 0.92058321]])

In [22]:
np.random.randn(5,5)

array([[-0.58343412,  0.7968133 , -0.47344566, -0.50694468, -0.87266486],
       [ 0.03522499,  0.50389256,  0.41075174, -1.11414151, -1.01601615],
       [ 0.13420407, -0.57869255,  0.87562415,  0.29418783,  0.10706462],
       [-0.65392865,  0.5011406 ,  0.6462031 ,  1.16812647,  1.62732623],
       [-0.35931129,  1.16188552, -0.12900563,  1.88388726,  1.10759003]])

In [ ]:
np.random.randint

In [23]:
np.random.randint(1,100)

44

In [24]:
np.random.randint(1,100,10)

array([35, 89, 34, 54, 60, 43,  5, 18, 35, 52])